FROM rust:1-slim-bullseye AS builder

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo build --release \
 && ls -lh /usr/src/app/target/release/

FROM debian:bullseye-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libssl1.1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/release/rust-app /app/rust-app

RUN ls -lh /app/

ENTRYPOINT ["/app/rust-app"]


