FROM rust:1-slim-bullseye AS builder

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && echo "fn main() { println!(\"cache bro\"); }" > src/main.rs

RUN apt-get update && apt-get install -y \
    curl \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/* \
    && cargo build --release

COPY src ./src

RUN cargo build --release

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/rust-app /app/rust-app

ENTRYPOINT ["/app/rust-app"]


